Добавление меток на карту
htmlacademy-javascript/1334129-keksobooking-21 pull request #2
Opened 2020-10-01 11:58 UTC by Cerasus04

2020-10-01 17:59 UTC, Spearance requested changes

2020-10-01 17:59 UTC, Spearance commented on js/main.js
> +  pin.style.left = `${obj.location.x + PIN.WIDTH / 2}px`;
нужно отнимать пол ширины и высоту, картинки дал в скайп

2020-10-01 17:59 UTC, Spearance commented on js/main.js
> +  pin.querySelector(`img`).src = obj.author.avatar;
элемент нужно выбрать в переменную, т.к. происходит два поиска по дом дереву, это затратно с точки зрения памяти

2020-10-01 17:59 UTC, Spearance commented on js/main.js
> +  return Array.from(new Set(randomArr));
Здесь непонятно, зачем из Set делать Array?

2020-10-01 17:59 UTC, Spearance commented on js/main.js
> +    (string === undefined) ? randomArr.push(arr[getRandomNumber(arr.length)]) : randomArr.push(string + arr[getRandomNumber(arr.length)]); // ругается на тернарный оператор, линтер хотел увидеть функ
в данном случае тернарный оператор не подходит, нужно использовать if, тернарный оператор используем только в присвоении

2020-10-01 17:59 UTC, Spearance commented on js/main.js
> +const getRandomArr = function (arr, number, string) {
получилась громоздкая функция, рекомендую погуглить функцию shuffleArray  или алгоритм 
Фишера–Йейтса

2020-10-04 09:45 UTC, Cerasus04 commented
Женя, пока ты консультировал, все нормально было, а вот, когда я начала делать рефактоинг, все посыпалось..
Если я в функции создания карточки не возвращаю массив return cards, а  просто вызываю функцию getCards(), все ломается..
Как я это делаю оставила в файле main1.js.
Поменяла на стрелочные функции, чтобы быть модной))),
вставила артикл с карточкой после формы,
причесала код в функции вывода карточки.

2020-10-05 08:02 UTC, merged